;Each new term in the Fibonacci sequence is generated by adding the 
;previous two terms. By starting with 1 and 2, the first 10 terms 
;will be:
;
;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
;Find the sum of all the even-valued terms in the sequence which do 
;not exceed four million.

(defun fibonacci-numbers (limit)
  (flet ((fib-iter (current-list)
                   (cons (+ (car current-list) 
                            (cadr current-list))
                         current-list)))
    (let ((current '(1 0)))
      (loop
        (setq current (fib-iter current))
        (when (> (car current) limit) (return (reverse (cdr current))))))))

(defun main ()
  (reduce #'+ (remove-if-not #'evenp (fibonacci-numbers 4000000))))
