--Each new term in the Fibonacci sequence is generated by adding the 
--previous two terms. By starting with 1 and 2, the first 10 terms 
--will be:
--
--1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
--Find the sum of all the even-valued terms in the sequence which do 
--not exceed four million.

fibList :: (Integral a) => a -> a -> [a]
fibList num1 num2 = sum:fibList num2 sum
    where sum = num1 + num2

fibonacci :: (Integral a) => [a]
fibonacci = fibList 0 1

main :: IO ()
main = print $ sum $ takeWhile smallEnough $ filter even fibonacci
    where smallEnough x = x < 4000000
