/*
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms 
will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do 
not exceed four million.
*/

#include <stdio.h>

int is_even(long);
long fibonacci_even_sum(long);

int is_even(long num) {
    return !(num % 2);
}

long fibonacci_even_sum(long limit) {
    long two_back = 0,
         one_back = 1,
         num = 0,
         sum = 0;

    while (num < limit) {
        num = two_back + one_back;
        if (is_even(num)) {
            sum += num;
        }
        two_back = one_back;
        one_back = num;
    }

    return sum;
}

int main() {
    printf("%ld\n", fibonacci_even_sum(4000000));
    return 0;
}
